# plugins:
  # - jekyll-sitemap
  # - jekyll-menus


# Outputting
permalink: pretty

prose:
  rooturl: '_posts'
  siteurl: 'http://kylemiller.com/'
  media: 'images'

# collections:
#   quotes:
#     output: true
#     permalink: quotes/:year/:month/:day/:title
